modules:
  data_collection:
    - path: modules.data_collection.ohlc_provider
      class: YahooFinanceProvider
      id: yahoo_finance
      config:
        symbols: ["AAPL", "MSFT", "GOOGL", "TSLA", "NVDA"]
        timeframe: "1d"
        lookback_days: 90

  strategies:
    - path: modules.strategies.martingale_dca
      class: MartingaleDCAStrategy
      id: martingale_dca
      config:
        equities_file: "data/equities.json"

  level_identification:
    - path: modules.level_identification.sr_detector
      class: SupportResistanceDetector
      id: sr_detector
      config:
        window_size: 10
        threshold: 0.03
        min_strength: 0.6
        max_levels: 8

  signal_generation:
    - path: modules.signal_generation.breakout_signal
      class: BreakoutSignalGenerator
      id: breakout_signal
      config:
        min_level_strength: 0.7
        confirmation_candles: 1
        signal_expiry_minutes: 120
      dependencies:
        price_data:
          type: data_collection
          id: yahoo_finance
        level_data:
          type: level_identification
          id: sr_detector

  risk_management:
    - path: modules.risk_management.position_sizing
      class: RiskManager
      id: risk_manager
      config:
        account_size: 10000
        risk_per_trade: 0.01
        max_position_size: 0.1
        stop_multiplier: 1.5
        target_rr_ratio: 2.0

  execution:
    - path: modules.execution.alpaca_executor
      class: AlpacaExecutor
      id: alpaca_executor
      config:
        api_key: "PK1OFRO428H1816RL1ZB"
        secret_key: "bh6N8csmX4wPSezI6yOTXvQJ2zzMnWM7K7wY9B4y"
        base_url: "https://paper-api.alpaca.markets/v2"

  ai:
    - path: modules.ai.portfolio_agent
      class: AIPortfolioAgent
      id: ai_portfolio_agent
      config:
        api_key: "sk-603ec7c27a91475885f137bc2c0be658"
        model: "deepseek-chat"
        base_url: "https://api.deepseek.com"

  monitoring:
    - path: modules.monitoring.performance_monitor
      class: PerformanceMonitor
      id: performance_monitor
      config:
        initial_capital: 10000
        update_interval: 60

  reporting:
    - path: modules.reporting.performance_reporter
      class: PerformanceReporter
      id: performance_reporter
      config:
        report_format: html
        save_path: reports/

  alerts:
    - path: modules.alerts.telegram_notifier
      class: TelegramNotifier
      id: telegram_notifier
      config:
        bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
        chat_id: "YOUR_CHAT_ID"