modules:
  ai:
  - class: AIPortfolioAgent
    config:
      api_key: sk-603ec7c27a91475885f137bc2c0be658
      base_url: https://api.deepseek.com
      model: deepseek-chat
    id: ai_portfolio_agent
    path: modules.ai.portfolio_agent
  alerts:
  - class: TelegramNotifier
    config:
      bot_token: 7817371175:AAEj3sTViuC8il4JqwEURentgyr2rq5ESCQ
      chat_id: '7817371175'
    id: telegram_notifier
    path: modules.alerts.telegram_notifier
  data_collection:
  - class: YahooFinanceProvider
    config:
      lookback_days: 90
      symbols:
      - AAPL
      - MSFT
      - GOOGL
      - TSLA
      - NVDA
      - BTC-USD
      - ETH-USD
      - GC=F      # Gold futures (supported)
      - SI=F      # Silver futures (supported)
      # Removed EURUSD=X, GBPUSD=X (not supported by Alpaca)
      timeframe: 1d
    id: yahoo_finance
    path: modules.data_collection.ohlc_provider
  execution:
  - class: AlpacaExecutor
    config:
      api_key: PK1OFRO428H1816RL1ZB
      base_url: https://paper-api.alpaca.markets
      secret_key: bh6N8csmX4wPSezI6yOTXvQJ2zzMnWM7K7wY9B4y
    id: alpaca_executor
    path: modules.execution.alpaca_executor
  level_identification:
  - class: SupportResistanceDetector
    config:
      max_levels: 8
      min_strength: 0.6
      threshold: 0.03
      window_size: 10
    id: sr_detector
    path: modules.level_identification.sr_detector
  monitoring:
  - class: PerformanceMonitor
    config:
      initial_capital: 10000
      update_interval: 60
    id: performance_monitor
    path: modules.monitoring.performance_monitor
  reporting:
  - class: PerformanceReporter
    config:
      report_format: html
      save_path: reports/
    id: performance_reporter
    path: modules.reporting.performance_reporter
  risk_management:
  - class: RiskManager
    config:
      account_size: 10000
      max_position_size: 0.1
      risk_per_trade: 0.01
      stop_multiplier: 1.5
      target_rr_ratio: 2.0
    id: risk_manager
    path: modules.risk_management.position_sizing
  signal_generation:
  - class: BreakoutSignalGenerator
    config:
      confirmation_candles: 1
      min_level_strength: 0.7
      signal_expiry_minutes: 120
    dependencies:
      level_data:
        id: sr_detector
        type: level_identification
      price_data:
        id: yahoo_finance
        type: data_collection
    id: breakout_signal
    path: modules.signal_generation.breakout_signal
  strategies:
  - class: MartingaleDCAStrategy
    config:
      equities_file: data/equities.json
    id: martingale_dca
    path: modules.strategies.martingale_dca